---
title: My dynamic report
output: html_fragment
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=FALSE, message=FALSE, warning=FALSE, error=FALSE)

```

```{css}
@import url('https://fonts.googleapis.com/css2?family=Frijole&family=Gamja+Flower&display=swap');
h1 {
  font-family: "Frijole";
  font-weight: 500;
  color: #20af31;
  background-color: #00541e;
}
h2 {
  font-family: "Frijole";
  font-weight: 400;
  color: #9deca6;
}
body {
  font-family: "Gamja Flower";
  color: #baf4c0;
  background-color: #00541e;
}
p {
    font-size: 25px;
}
a {
    color: #00ff1d;
}
```

```{r}
library(tidyverse)
#Create data frame
logged_data <- read_csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vRpmmeFRIl3s5FC4I2eYuIagto6C4N40-ImnU8Up9qQs67rGHGXFOiTLtApqltKvxjUTPsQAjF08F6s/pub?output=csv") %>% 
  rename(Timestamp = 1, 
       Show_Watching_Frequency = 2, 
       Average_Hours_Watched = 3, 
       Preferred_Device = 4, 
       Recent_Content_Type = 5, 
       Watching_Reason = 6, 
       Preferred_Platform_Reason = 7)
latest_data <- logged_data
```

## Plot one & Summary

```{r}
#Plot 1
ggplot(data = latest_data) +
  geom_bar(aes(y = Average_Hours_Watched), fill = "#40E0D0") +
  labs(
    title = "Distribution of Average Hours Watched",
    x = "Average Hours Watched",
    y = "Hours per day"
  ) +
  theme_minimal() +
  theme(
    panel.background = element_rect(fill = "#daf5f2"),
    plot.title = element_text(hjust = 0.5)
  )

#Summary data 1
max_Hours = max(latest_data$Average_Hours_Watched)
min_Hours = min(latest_data$Average_Hours_Watched)
mean_Hours = mean(latest_data$Average_Hours_Watched)

#Summary 1
paste("The maximum average time of show watched is", max_Hours,"hours per day.", 
      "The minimum average time of show watched is", min_Hours,"hours per day.", 
      "The mean average time of show watched is", mean_Hours, "hours per day.")
```
## Plot two & Summary

```{r}
#Plot 2
ggplot(data = latest_data) +
  geom_bar(aes(x = Preferred_Device), fill = "#40E0D0") +
  labs(
    title = "Distribution of Preferred Device",
    x = "Device used",
    y = "Count"
  ) +
  theme_minimal() +
  theme(
    panel.background = element_rect(fill = "#daf5f2"),
    plot.title = element_text(hjust = 0.5)
  )

#Summary data 2
device_counts = table(latest_data$Preferred_Device)
most_used = names(which.max(device_counts))
most_used_c = max(device_counts)
least_used = names(which.min(device_counts))
least_used_c = min(device_counts)

#Summary 2
paste0("The most used device for show watching is ", most_used, ", used by ", most_used_c, " people. \n",
       "The least used device for show watching is ", least_used, ", used by ", least_used_c, " people.")
```

